import Head from 'next/head'
import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Card, Carousel, Col, Divider, Image, Layout, Row, Space, Typography } from 'antd';
import BaseLayout from '../../components/BaseLayout/BaseLayout.component';

import config from './About.config';
import css from './About.module.scss';

const ar = [1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0]

const { Sider } = Layout;
const { Title, Text, Paragraph } = Typography;

const About = (props) => {
  const renderCarouselItems = () => (
    <div style={{ height: '50vh'}}>
      <Row align="top" justify="center">
        <Col xs={24} md={12} lg={12}>
          <div style={{ margin: '0 5vw' }}>
            <Image
              alt="self_img_01"
              src="/images/self_img_01.png"
              preview={false}
              width="50%"
            />
          </div>
        </Col>
        <Col xs={24} md={12} lg={12}>
          <div style={{ margin: '0 5vw', textAlign: 'justify' }}>
            <Title level={2}>About Wisnu</Title>
            <Paragraph>
              Amet dui, dictum nunc leo netus Leo, eu commodo nulla fames euismod lacus sed eget, purus vestibulum, ultricies magnis cras et.
              Natoque Elit lectus arcu platea ligula euismod cursus, congue nec dictumst pede cubilia malesuada feugiat dictumst magnis iaculis sit platea hendrerit.
              Lacus fames enim feugiat quam per gravida iaculis.
            </Paragraph>
          </div>
        </Col>
      </Row>
    </div>
  );

  const renderCardCols = (type) => (
    <Col xs={24} md={12} lg={6}>
      <Card
        hoverable
        cover={<div style={{ minHeight: '450px' }}>
          <Image
            alt={type === 1 ? "red_crescent_moon" : "self_img_01"}
            src={type === 1 ? "/images/red_crescent_moon.jpg" : "/images/self_img_01.png"}
            preview={false}
            width="100%"
          />
        </div>}
        style={{ backgroundColor: 'black', border: '3px solid white' }}
        // title={<Title level={3}>Sample App</Title>}
      >
        <Card.Meta
          title={<Title level={3}><i>Sample App</i></Title>}
          description={<Paragraph>Sample app description</Paragraph>}
        />
        {/* <Image
          alt="red_crescent_moon"
          src="/images/red_crescent_moon.jpg"
          preview={false}
          width="50%"
        /> */}
        Content
      </Card>
    </Col>
  );

  return (
    <div id={css.AboutContainer}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <div style={{ padding: '5vh 5vw' }}>
        <Title level={2}>KONTOL</Title>
        <Row gutter={[32,32]} align="top">
          {renderCardCols(1)}
          {renderCardCols()}
          {renderCardCols()}
          {renderCardCols(1)}
          {renderCardCols(1)}
          {renderCardCols()}
          {renderCardCols(1)}
          {renderCardCols()}
          {renderCardCols(1)}
          {renderCardCols(1)}
        </Row>
      </div>
      
      {/* <Space direction="vertical" size="large">
        <Row align="top" justify="center">
          <Col xs={24} md={12}} lg={12}>
            <div style={{ margin: '0 5vw' }}>
              <Image
                alt="self_img_01"
                src="/images/self_img_01.png"
                preview={false}
                width="100%"
              />
            </div>
          </Col>
          <Col xs={24} md={12}} lg={12}>
            <div style={{ margin: '0 5vw', textAlign: 'justify' }}>
              <Title level={2}>About Wisnu</Title>
              <Paragraph>
                Amet dui, dictum nunc leo netus Leo, eu commodo nulla fames euismod lacus sed eget, purus vestibulum, ultricies magnis cras et.
                Natoque Elit lectus arcu platea ligula euismod cursus, congue nec dictumst pede cubilia malesuada feugiat dictumst magnis iaculis sit platea hendrerit.
                Lacus fames enim feugiat quam per gravida iaculis.
                Penatibus nostra leo litora nostra massa metus odio.
                Cras auctor ligula sociosqu, dictum gravida a erat.
                At netus vehicula vivamus aliquam dapibus neque magnis dapibus lacus pharetra aliquam egestas tortor volutpat nascetur class.
                Nisl proin condimentum bibendum nunc lacus potenti aliquam lacinia dis ullamcorper curae;.
                Vulputate laoreet nonummy tincidunt vivamus est luctus curae;. Sodales nibh ultrices vel turpis.
                Montes quisque, nec donec quis diam ac donec nunc malesuada aptent nam, ac leo sociis ullamcorper convallis sed scelerisque proin hendrerit volutpat Dignissim egestas fusce tortor. Fames curabitur facilisis hendrerit eu.
                Odio.
                Mi gravida ullamcorper magna posuere nisl.
                Convallis sit et diam vulputate nonummy morbi lorem sociosqu sed eros lorem mauris et enim.
                Cum accumsan nostra fusce. Volutpat aliquam ut ad litora rutrum dolor etiam mollis gravida.
                Varius sociosqu pulvinar sagittis eget facilisis pulvinar. Quis aliquam Lacus ante.
              </Paragraph>
            </div>
          </Col>
        </Row>
        <Divider className={css["section-divider"]} />
        <Row align="top" justify="center">
          <Col xs={24} md={12} xl={12}>
            <div style={{ margin: '0 5vw' }}>
              <Title level={2}></Title>
            </div>
          </Col>
          <Col xs={24} md={12} xl={12}>
            <div style={{ margin: '0 5vw', textAlign: 'right' }}>
              <Image
                alt="self_img_01"
                src="/images/red_crescent_moon.jpg"
                preview={false}
                width="50%"
              />
            </div>
          </Col>
        </Row>
      </Space> */}
    </div>
  );
};

About.displayName = config.displayName;
About.defaultProps = config.defaultProps;

export default About;