import Head from 'next/head'
// import Image from 'next/image'
import { useRouter } from 'next/router';
import React from 'react';
import parse from 'html-react-parser';
import { Col, Divider, Image, Row, Space, Typography } from 'antd';

import config from './Home.config';
import css from './Home.module.scss'

const { Paragraph, Text, Title } = Typography;

const Home = (props) => {
  const bannerContent = `<h1><b>Hi there, Wisnu here. I'm a web developer specializing in front end development</b></h1>
  <p>I believe that over-engineered solutions are just as detrimental as under-engineered solutions, regardless of the field.
  However, I also believe that applying a good project structure right from the start would spare us unnecessary troubles down the line.</p>
  <p>That being said, please navigate around, I sincerely hope that you'll find something interesting.
  Finally, looking forward to future collaborations...</p><br/><br/><br/><br/><br/>Regards,<br/><b>Wisnu</b>`;

  const [animatedBannerContent, setAnimatedBannerContent] = React.useState(``);

  React.useEffect(() => {
    setTimeout(() => {
      const animatedBannerContentLength = animatedBannerContent.length;
      const appendedChar = bannerContent[animatedBannerContentLength];
      if (appendedChar) {
        const newAnimatedBannerContent = `${animatedBannerContent}${appendedChar}`;
        setAnimatedBannerContent(newAnimatedBannerContent)
      };
    }, 40);
  }, [animatedBannerContent]);

  const parserOpt = {
    replace: (domNode) => {
      if (domNode.attribs && domNode.attribs.class === 'remove') {
        return <></>;
      }
    }
  };

  return (
    <div id={css.HomeContainer}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Space direction="vertical" size="large">
        <Row align="top" justify="center" id={css.HeroSection}>
          <Col span={24}>
            <div style={{ padding: '2.5vh 5vw', fontFamily: 'monospace' }}>
              {parse(animatedBannerContent, parserOpt)}
            </div>
          </Col>
        </Row>
        <Divider hidden className={css["section-divider"]} />
        <Row align="top" justify="center">
          <Col xs={24} md={24} lg={12}>
            <div style={{ margin: '1vh 5vw' }}>
              <Image
                alt="self_img_01"
                src="/images/self_img_01.png"
                preview={false}
                width="100%"
              />
              <Text style={{ fontSize: 12 }}>Photographed by <i>Fauzan Razansyah</i></Text>
            </div>
          </Col>
          <Col xs={24} md={24} lg={12}>
            <div style={{ margin: '1vh 5vw', textAlign: 'justify' }}>
              <Title level={2} style={{ textAlign: 'right' }}>A Bit About Me</Title>
              <Paragraph>
                I'm a front end developer with approximately 9 months of professional experience in web-app development.
                I'm currently employed as a part of the IT product team of a digital marketing agency.
                Not to be mistaken as someone who handles a client's website, my role is to perform RnD which the end products are web-apps that provides aid for enterprise to assist their business needs.
                Within those 9 months, I've participated in the development of <i>Dashboards</i>, <i>LMS</i>, <i>KMS</i>, and <i>Invoicing</i> interfaces (which all happened to be <i>ReactJS</i>-based).
                So far, I've managed to somehow established my own development principles by also taking my colleagues' opinions into account.
                Applying said principles had saved me from having to refactor or develop new features in unnecessarily long time.
                Last but not least, I believe that communication skill is important for a product team member regardless of their specialization inside the team.
              </Paragraph>
            </div>
          </Col>
        </Row>
      </Space>
    </div>
  )
}

Home.displayName = config.displayName;
Home.defaultProps = config.defaultProps;

export default Home;